#! /bin/bash
#This script is designed to find hosts with common port that are installed on their system
nmap -sT <targeted IP> -p <targeted port#> >/dev/null -oG SScan

cat SScan | grep open > Stext 

cat Stext 
